services:
  app:
    build:
      context: .
      args:
        - DEV=${DEV}
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DB_URL}
      - BOOKS_ARCHIVES_PATH="/books"
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
      - DEV=${DEV}
    ports:
      - "8000:9000"
    volumes:
      - ./app:/app
      - ./books:/books
      - ./library.db:/app/library.db
